- name: Install Ansible
  homebrew: name=ansible

- name: Install Vagrant
  homebrew_cask: name=vagrant

- name: Install Google Cloud SDK
  homebrew_cask: name=google-cloud-sdk

- name: Install vim plugins
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
  with_items:
    - {repo: "https://github.com/pearofducks/ansible-vim.git", dest: ansible-vim}
