- name: Install 1Password password manager
  homebrew_cask: name=1password

- name: Install postman
  homebrew_cask: name=postman

- name: Install TablePlus database management tool
  homebrew_cask: name=tableplus

- name: Install psql client
  homebrew: name=libpq

- name: Add psql to bin
  lineinfile: dest=~/.zshrc line='export PATH="/opt/homebrew/opt/libpq/bin:$PATH"'

- name: Install miro collaboration whiteboard
  homebrew_cask: name=miro

- name: Install Alfred productivity utility
  homebrew_cask: name=alfred

- name: Install mounty for NTFS volumes
  homebrew_cask: name=mounty

- name: Install The Unarchiver
  homebrew_cask: name=the-unarchiver

- name: Install App Cleaner
  homebrew_cask: name=appcleaner

- name: Install flycut clipboard manager
  homebrew_cask: name=flycut

- name: Install clocker timezone menu
  homebrew_cask: name=clocker

- name: Install Google Drive
  homebrew_cask: name=google-drive
