- name: Install newer bash
  homebrew: name=bash

- name: Install ohmyzsh
  shell: /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

- name: Setup ohmyzsh theme
  lineinfile:
    path: ~/.zshrc
    regexp: '^(.*)ZSH_THEME="(.*)"$'
    line: 'ZSH_THEME="gnzh"'
    backrefs: yes

- name: Install core GNU utilities
  homebrew: name=coreutils

- name: Install GNU implementation of sed
  homebrew: name=gnu-sed

- name: Install tool for working with Architecture Decision Records
  homebrew: name=adr-tools

- name: Install zsh-completions
  homebrew: name=zsh-completions

- name: Setup zsh-completions
  blockinfile:
    create: yes
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK (BASH_COMPLETION)"
    block: |
      if type brew &>/dev/null; then
      FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

      autoload -Uz compinit
      compinit
      fi

- name: Install tmux terminal multiplexer
  homebrew: name=tmux

- name: Setup tmux
  blockinfile:
    create: yes
    path: ~/.tmux.conf
    block: |
      bind c new-window -c "#{pane_current_path}"
      bind '"' split-window -c "#{pane_current_path}"
      bind % split-window -h -c "#{pane_current_path}"

- name: Start tmux by default in Terminal.app
  blockinfile:
    path: ~/.zshrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK (tmux start)"
    block: |
      TERM=xterm &&
      if [ "$TMUX" = "" ]; then tmux; fi

- name: Install icdiff side-by-side diff tool
  homebrew: name=icdiff

- name: Install watch for repeating command line commands
  homebrew: name=watch

- name: Install topgrade
  homebrew: name=topgrade

- name: Install htop for process monitoring
  homebrew: name=htop

- name: Install iftop for network monitoring
  homebrew: name=iftop

- name: Install NCurses Disk Usage utility
  homebrew: name=ncdu

- name: Install pqrs command line tool for inspecting Parquet files
  homebrew: name=manojkarthick/tap/pqrs
