- name: Install nvm for node version management
  homebrew: name=nvm

- name: Add nvm to .zshrc
  lineinfile: dest=~/.zshrc line='{{ item }}' create=yes
  with_items:
    - export NVM_DIR="$HOME/.nvm"
    - . "$(brew --prefix nvm)/nvm.sh"

- name: Install Node.js LTS
  shell: export NVM_DIR="$HOME/.nvm" && . "$(brew --prefix nvm)/nvm.sh" && nvm install v18.13.0

- name: Setup to use LTS
  shell: export NVM_DIR="$HOME/.nvm" && . "$(brew --prefix nvm)/nvm.sh" && nvm use v18.13.0

- name: Set default node version for NVM
  shell: export NVM_DIR="$HOME/.nvm" && . "$(brew --prefix nvm)/nvm.sh" && nvm alias default node

- name: Install Electron Packager
  shell: export NVM_DIR="$HOME/.nvm" && . "$(brew --prefix nvm)/nvm.sh" && $HOME/.nvm/versions/node/v18.13.0/bin/npm install electron-packager@13.0.1 --global

- name: Install Yarn
  shell: export NVM_DIR="$HOME/.nvm" && . "$(brew --prefix nvm)/nvm.sh" && $HOME/.nvm/versions/node/v18.13.0/bin/npm install yarn@1.21.1 --global

- name: Install vim plugin
  git: repo={{ item.repo }} dest=~/.vim/bundle/{{ item.dest }}
  with_items:
    - {repo: "https://github.com/pangloss/vim-javascript.git", dest: vim-javascript}
